export const doctors = [
  {
    name: "Dr. Anjali Kapoor",
    email: "anjali.kapoor@mediqueue.com",
    password: "Doctor@123",
    image: "doc1.jpg",
    speciality: "General physician",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Kapoor has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: { line1: "Gomti Nagar", line2: "Lucknow, Uttar Pradesh" },
  },
  {
    name: "Dr. Rajesh Verma",
    email: "rajesh.verma@mediqueue.com",
    password: "Doctor@123",
    image: "doc2.jpg",
    speciality: "Gynecologist",
    degree: "MBBS",
    experience: "3 Years",
    about:
      "Dr. Verma has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 600,
    address: { line1: "Sector 18", line2: "Noida, Uttar Pradesh" },
  },
  {
    name: "Dr. Amit Bansal",
    email: "amit.bansal@mediqueue.com",
    password: "Doctor@123",
    image: "doc3.jpg",
    speciality: "Dermatologist",
    degree: "MBBS",
    experience: "1 Years",
    about:
      "Dr. Bansal has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 300,
    address: { line1: "Koramangala", line2: "Bengaluru, Karnataka" },
  },
  {
    name: "Dr. Sunita Sharma",
    email: "sunita.sharma@mediqueue.com",
    password: "Doctor@123",
    image: "doc4.jpg",
    speciality: "Pediatricians",
    degree: "MBBS",
    experience: "2 Years",
    about:
      "Dr. Sharma has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 400,
    address: { line1: "Vasant Kunj", line2: "New Delhi, Delhi" },
  },
  {
    name: "Dr. Vikram Singh",
    email: "vikram.singh@mediqueue.com",
    password: "Doctor@123",
    image: "doc5.jpg",
    speciality: "Neurologist",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Singh has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: { line1: "Civil Lines", line2: "Jaipur, Rajasthan" },
  },
  {
    name: "Dr. Rahul Malhotra",
    email: "rahul.malhotra@mediqueue.com",
    password: "Doctor@123",
    image: "doc6.jpg",
    speciality: "Gastroenterologist",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Malhotra has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: { line1: "Bandra West", line2: "Mumbai, Maharashtra" },
  },
  {
    name: "Dr. Priya Desai",
    email: "priya.desai@mediqueue.com",
    password: "Doctor@123",
    image: "doc7.jpg",
    speciality: "General physician",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Desai has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: { line1: "Navrangpura", line2: "Ahmedabad, Gujarat" },
  },
  {
    name: "Dr. Manoj Kumar",
    email: "manoj.kumar@mediqueue.com",
    password: "Doctor@123",
    image: "doc8.jpg",
    speciality: "Gynecologist",
    degree: "MBBS",
    experience: "3 Years",
    about:
      "Dr. Kumar has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 600,
    address: { line1: "Salt Lake City", line2: "Kolkata, West Bengal" },
  },
  {
    name: "Dr. Neha Gupta",
    email: "neha.gupta@mediqueue.com",
    password: "Doctor@123",
    image: "doc9.jpg",
    speciality: "Dermatologist",
    degree: "MBBS",
    experience: "1 Years",
    about:
      "Dr. Gupta has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 300,
    address: { line1: "Jubilee Hills", line2: "Hyderabad, Telangana" },
  },
  {
    name: "Dr. Aakash Roy",
    email: "aakash.roy@mediqueue.com",
    password: "Doctor@123",
    image: "doc10.jpg",
    speciality: "Pediatricians",
    degree: "MBBS",
    experience: "2 Years",
    about:
      "Dr. Roy has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 400,
    address: { line1: "Anna Nagar", line2: "Chennai, Tamil Nadu" },
  },

  {
    name: "Dr. Arun Joshi",
    email: "arun.joshi@mediqueue.com",
    password: "Doctor@123",
    image: "doc11.jpg",
    speciality: "Neurologist",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Joshi has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: {
      line1: "Shivaji Nagar",
      line2: "Pune, Maharashtra",
    },
  },
  {
    name: "Dr. Sameera Khan",
    email: "sameera.khan@mediqueue.com",
    password: "Doctor@123",
    image: "doc12.jpg",
    speciality: "Neurologist",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Khan has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: {
      line1: "Aligarh Road",
      line2: "Agra, Uttar Pradesh",
    },
  },
  {
    name: "Dr. Vivek Chawla",
    email: "vivek.chawla@mediqueue.com",
    password: "Doctor@123",
    image: "doc13.jpg",
    speciality: "General physician",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Chawla has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 500,
    address: {
      line1: "Model Town",
      line2: "Ludhiana, Punjab",
    },
  },
  {
    name: "Dr. Ravina Mehta",
    email: "ravina.mehta@mediqueue.com",
    password: "Doctor@123",
    image: "doc14.jpg",
    speciality: "Gynecologist",
    degree: "MBBS",
    experience: "3 Years",
    about:
      "Dr. Mehta has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 600,
    address: {
      line1: "Maninagar",
      line2: "Surat, Gujarat",
    },
  },
  {
    name: "Dr. Suresh Reddy",
    email: "suresh.reddy@mediqueue.com",
    password: "Doctor@123",
    image: "doc15.jpg",
    speciality: "Dermatologist",
    degree: "MBBS",
    experience: "1 Years",
    about:
      "Dr. Reddy has a strong commitment to delivering comprehensive medical care, focusing on preventive medicine, early diagnosis, and effective treatment strategies.",
    fees: 300,
    address: {
      line1: "Banjara Hills",
      line2: "Hyderabad, Telangana",
    },
  },
  {
    name: "Dr. Deepak Sharma",
    email: "deepak.sharma@mediqueue.com",
    password: "Doctor@123",
    image: "doc16.jpg",
    speciality: "General physician",
    degree: "MBBS",
    experience: "5 Years",
    about:
      "Dr. Sharma focuses on holistic primary care with strong emphasis on lifestyle management, preventive health, and early diagnosis of chronic illnesses.",
    fees: 400,
    address: {
      line1: "Indiranagar",
      line2: "Bengaluru, Karnataka",
    },
  },
  {
    name: "Dr. Meera Nanda",
    email: "meera.nanda@mediqueue.com",
    password: "Doctor@123",
    image: "doc17.jpg",
    speciality: "Neurologist",
    degree: "MBBS",
    experience: "6 Years",
    about:
      "Dr. Nanda specializes in neurological disorders including migraines, epilepsy, and nerve-related conditions with patient-centric care.",
    fees: 700,
    address: {
      line1: "Saket",
      line2: "New Delhi, Delhi",
    },
  },
  {
    name: "Dr. Avni Jain",
    email: "avni.jain@mediqueue.com",
    password: "Doctor@123",
    image: "doc18.jpg",
    speciality: "Gynecologist",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Jain provides comprehensive women’s healthcare with expertise in pregnancy care, fertility counseling, and preventive gynecology.",
    fees: 600,
    address: {
      line1: "Malviya Nagar",
      line2: "Jaipur, Rajasthan",
    },
  },
  {
    name: "Dr. Ritu Agarwal",
    email: "ritu.agarwal@mediqueue.com",
    password: "Doctor@123",
    image: "doc19.jpg",
    speciality: "Dermatologist",
    degree: "MBBS",
    experience: "3 Years",
    about:
      "Dr. Agarwal treats skin, hair, and nail conditions with a modern approach combining clinical dermatology and cosmetic care.",
    fees: 500,
    address: {
      line1: "Hazaratganj",
      line2: "Lucknow, Uttar Pradesh",
    },
  },
  {
    name: "Dr. Vineeta Choudhary",
    email: "vineeta.choudhary@mediqueue.com",
    password: "Doctor@123",
    image: "doc20.jpg",
    speciality: "Pediatricians",
    degree: "MBBS",
    experience: "5 Years",
    about:
      "Dr. Choudhary is dedicated to child healthcare, focusing on growth monitoring, vaccinations, and pediatric wellness.",
    fees: 450,
    address: {
      line1: "Civil Lines",
      line2: "Prayagraj, Uttar Pradesh",
    },
  },
];
